### ISSUE TITLE
BugBounty: inconsistency in return functions and real swaps

### ISSUE THREAD

**Issue by Upaut1** [SoyFinance/smart-contracts#2]

**Comment by Dexaran** [comment]
The discussion of this issue is going on dedicated Telegram channel

**Comment by yuriy77k** [comment]
Issue not confirmed.

**Comment by Upaut1** [comment]
Функции getAmountsOut и getAmountsIn в [SoyFinanceRouter.sol](https://github.com/SoyFinance/smart-contracts/blob/main/SoyFinanceRouter.sol) никак не проверяют маршрут на наличие повторяющихся адресов пар (пулов). При вызове этих функций на чтение я буду видеть сколько токенов я получу на выходе, но в действительности при реальных свопах маршрут с повторяющимися парами не пройдет, в пределах одной транзакции, разумеется. Такая транзакция будет отклонена.
Если по правильному, то функции getAmountsOut и getAmountsIn, при чтении контракта,  должны давать ошибку при использовании в маршруте повторяющихся пар, а не выводить данные которые в действительности не могут быть исполнены.

**Comment by yuriy77k** [comment]
Так как эта особенность не несет риска для пользователей

**Comment by Upaut1** [comment]
Я Вас услышал. Тема закрыта.
