### ISSUE TITLE
Price error

### ISSUE THREAD

**Issue by Sgseelan** [SoyFinance/smart-contracts#5]
CLO and wrapped clo price is different

In Pancakeswap 10000 clo is 85$

In soy finance 10000 clo is 95$

**Comment by Upaut1** [comment]
There is no error!
Take up arbitrage if the commission for using the bridge is lower than the profit you receive

**Comment by Dexaran** [comment]
@Sgseelan this is not a technical issue in any case. I'm closing this thread for now
