### ISSUE TITLE
BugBounty: Ошибка в данных у некоторых транзакций

### ISSUE THREAD

**Issue by Upaut1** [SoyFinance/smart-contracts#6]
Объясню на примере двух торговых транзакций.
[первая транзакция](https://explorer.callisto.network/tx/0xd3c9074591491e8bdeffc2d5ff611693cf9d0793384d437695d8f6a82b48069b/token-transfers) использует функцию swapExactTokensForTokens(uint256 amountIn, uint256 amountOutMin, address[] path, address to, uint256 deadline), рассмотрим входные HEX-данные у этой транзакции:

0x38ed1739000000000000000000000000000000000000000000000000002386f26fc10000000000000000000000000000000000000000000000000000008233e9f4177c9100000000000000000000000000000000000000000000000000000000000000**a0**000000000000000000000000fc8f3324b6d71d14bfd625ecdbd18f3bc29a9935000000000000000000000000000000000000000000000000000000006134ebc200000000000000000000000000000000000000000000000000000000000000030000000000000000000000006182d2cd59227c20b486a53976dceeaf38e76eed000000000000000000000000c63c95d1d4f945141fe86ef978d6b99b8e3905d50000000000000000000000001eaa43544daa399b87eecfcc6fa579d5ea4a6187

В этих данных указано что адреса 20-байтовые (значение a0, что выделено жирным в данных)
Если я все правильно понимаю, то здесь все правильно и корректно.

А теперь рассмотрим [вторую транзакцию](https://explorer.callisto.network/tx/0x49975b562a9a9fa68cd6be9d377a1c8adf4de9e47c6917ffcd93b31aec4a671d/token-transfers) которая использует функцию swapExactETHForTokens(uint256 amountOutMin, address[] path, address to, uint256 deadline), теперь рассмотрим входные HEX-данные у этой транзакции:

0x7ff36ab500000000000000000000000000000000000000000000004aab2b57ba67e730cf00000000000000000000000000000000000000000000000000000000000000**80**000000000000000000000000847ff0613ea669314dd5e295ebd48cc3bfc9035800000000000000000000000000000000000000000000000000000000613595c40000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c63c95d1d4f945141fe86ef978d6b99b8e3905d50000000000000000000000001eaa43544daa399b87eecfcc6fa579d5ea4a6187

В этих данных указано что адреса 16-байтовые (значение 80, что выделено жирным в данных).

Если я все правильно понимаю, то торговые функции где используется CLO в качестве входа (swapETHForExactTokens, swapExactETHForTokens, ) имеют неправильные данные

**Comment by yuriy77k** [comment]
Параметры кодируются согласно спецификации: https://docs.soliditylang.org/en/v0.6.10/abi-spec.html
Там нет ошибки

**Comment by Upaut1** [comment]
Да, согласен с Вами. Посмотрел спецификацию, как оказалось это не размерность адреса, а смещение до данных.
Тема закрыта.
